### ISSUE TITLE
PCheckerdfs_image_transfer_timeout12.jimple 

### ISSUE THREAD

**Issue by popacai** [tianyin/conquid#6]
INFO  - >>No.12
INFO  - -------statement:$i4 = virtualinvoke r1.<org.apache.hadoop.conf.Configuration: int getInt(java.lang.String,int)>("dfs.image.transfer.timeout", 60000) returned
INFO  - -------statement:r0 := @parameter0: java.net.HttpURLConnection FLAG: 
INFO  - -------statement:<org.apache.hadoop.hdfs.server.namenode.TransferFsImage: int timeout> = $i4 FLAG: 
INFO  - -------statement:$i3 = <org.apache.hadoop.hdfs.server.namenode.TransferFsImage: int timeout> FLAG: 
INFO  - -------statement:virtualinvoke r0.<java.net.HttpURLConnection: void setReadTimeout(int)>($i3) 2invoke

**Comment by popacai** [comment]
2 cases

**Comment by popacai** [comment]
statement:r0 := @parameter0: java.net.HttpURLConnection FLAG:  is not a correct stmt

**Comment by tianyin** [comment]
what do you mean?

**Comment by popacai** [comment]
caused by "https://github.com/tianyin/conquid/issues/13"

close duplicate issue
